- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
  tasks:
    - name: Hello Message sesond
      debug:
        msg: "Hello World! again"        

